FROM python
RUN pip install flask
RUN pip install Faker
EXPOSE 5000
CMD python3 /home/myapp/FlaskDevOps.py
FROM python
RUN pip install flask
RUN pip install Faker
EXPOSE 5000
CMD python3 /home/myapp/FlaskDevOps.py
FROM python
RUN pip install flask
RUN pip install Faker
COPY FlaskDevOps.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/FlaskDevOps.py
FROM python
RUN pip install flask
RUN pip install Faker
COPY FlaskDevOps.py /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/FlaskDevOps.py
